### ISSUE TITLE
Please specify license for rubygems.org

### ISSUE THREAD

**Issue by pvalena** [socketry/http-accept#10]
In License field it says:
N/A

**Comment by pvalena** [comment]
Please also include the License file in your repo.

**Comment by havenwood** [comment]
The MIT license was recently added to the gemspec in 248b5b97927a7f12f1be7be9de169af6bf5331da. Instead of a discrete LICENSE file, the license is at the bottom of the README.md.

**Comment by pvalena** [comment]
Yes, sorry, I've noticed both after I wrote this issue. Would be nice if it was populated [rubygems] though, which requires an update; and standalone license would be also nice, but feel free not to have any.

Thanks!

**Comment by ioquatix** [comment]
I can push an update. Btw where are you coming from? Suddenly this gem had some
Interest/activity.

**Comment by pvalena** [comment]
> I can push an update. Btw where are you coming from? Suddenly this gem had some
> Interest/activity.

Thanks. In what sense? Literally I'm from Czech Republic. Rhetorically I'm looking into packaging gem this in Fedora, as it's needed for `rest-client` [gem 2.1.0](https://rubygems.org/gems/rest-client).

**Comment by ioquatix** [comment]
Great, thanks for the information.

I pushed the update.
