### ISSUE TITLE
Gemspec does not specify license

### ISSUE THREAD

**Issue by rob-as** [socketry/http-accept#8]
# Issue description

When running `gem build http-accept.gemspec` on `master` I get the following warning

```
WARNING:  licenses is empty, but is recommended.  Use a license identifier from
http://spdx.org/licenses or 'Nonstandard' for a nonstandard license.
```

Furthermore the missing license attribute causes unnecessary errors when the gem is checked by tools like [LicenseFinder](https://github.com/pivotal/LicenseFinder).

# Expected behaviour

The gemspec includes a license attribute declaring the license as `MIT` as stated in the [README](https://github.com/socketry/http-accept#license).

**Comment by ioquatix** [comment]
thanks!
